
// This file has been generated by the GUI designer. Do not modify.
namespace LandniteLauncherGtk
{
	public partial class SplashScreen
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label splashScreenLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget LandniteLauncherGtk.SplashScreen
			this.Name = "LandniteLauncherGtk.SplashScreen";
			this.Title = global::Mono.Unix.Catalog.GetString("Landnite");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child LandniteLauncherGtk.SplashScreen.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.splashScreenLabel = new global::Gtk.Label();
			this.splashScreenLabel.Name = "splashScreenLabel";
			this.splashScreenLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Loading Landnite Client...");
			this.splashScreenLabel.Justify = ((global::Gtk.Justification)(2));
			this.fixed1.Add(this.splashScreenLabel);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.splashScreenLabel]));
			w1.X = 140;
			w1.Y = 140;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
