
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button playButton;

	private global::Gtk.Button aboutButton;

	private global::Gtk.Button changeDirectoryButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 242;
		this.HeightRequest = 147;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Landnite");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.DefaultWidth = 237;
		this.DefaultHeight = 138;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.playButton = new global::Gtk.Button();
		global::Gtk.Tooltips w1 = new Gtk.Tooltips();
		w1.SetTip(this.playButton, "Play Landnite.", "Play Landnite.");
		this.playButton.WidthRequest = 185;
		this.playButton.HeightRequest = 60;
		this.playButton.CanFocus = true;
		this.playButton.Name = "playButton";
		this.playButton.UseUnderline = true;
		this.playButton.Label = global::Mono.Unix.Catalog.GetString("PLAY");
		this.fixed1.Add(this.playButton);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.playButton]));
		w2.X = 29;
		w2.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.aboutButton = new global::Gtk.Button();
		w1.SetTip(this.aboutButton, "About Landnite Launcher.", "About Landnite Launcher.");
		this.aboutButton.WidthRequest = 50;
		this.aboutButton.CanFocus = true;
		this.aboutButton.Name = "aboutButton";
		this.aboutButton.UseUnderline = true;
		this.aboutButton.Label = global::Mono.Unix.Catalog.GetString("About");
		this.fixed1.Add(this.aboutButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.aboutButton]));
		w3.X = 165;
		w3.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.changeDirectoryButton = new global::Gtk.Button();
		w1.SetTip(this.changeDirectoryButton, "Change where the program searches for your game incase you have it installed else" +
				"where.", "Change where the program searches for your game incase you have it installed else" +
				"where.");
		this.changeDirectoryButton.WidthRequest = 120;
		this.changeDirectoryButton.HeightRequest = 0;
		this.changeDirectoryButton.CanFocus = true;
		this.changeDirectoryButton.Name = "changeDirectoryButton";
		this.changeDirectoryButton.UseUnderline = true;
		this.changeDirectoryButton.Label = global::Mono.Unix.Catalog.GetString("Change Directory");
		this.fixed1.Add(this.changeDirectoryButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.changeDirectoryButton]));
		w4.X = 29;
		w4.Y = 103;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.playButton.Clicked += new global::System.EventHandler(this.playButtonClicked);
		this.aboutButton.Clicked += new global::System.EventHandler(this.aboutButtonClicked);
		this.changeDirectoryButton.Clicked += new global::System.EventHandler(this.changeDirectoryClicked);
	}
}
